[phases.setup]
nixPkgs = ["maven", "jdk21"]

[phases.install]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Xmx512m -Xms256m -jar target/car-repair-shop-0.0.1-SNAPSHOT.jar"

[variables]
SPRING_PROFILES_ACTIVE = "prod"

